# set the activation key
unbind C-b
set -g prefix `
bind-key ` send-prefix  # escape hatch: `` sends a single `

# other key bindings
bind-key space next-window
bind-key '|' split-window -h
bind-key _ split-window

bind-key -n C-S-Left swap-window -t -1\; select-window -t -1
bind-key -n C-S-Right swap-window -t +1\; select-window -t +1

# Set status bar
set -g status-bg black
set -g status-fg white
set -g status-right "#{=22:pane_title} %m/%d %l:%M%p"


# highlight the currently active window
set-window-option -g window-status-current-style fg=black
set-window-option -g window-status-current-style bg=red
# do not need to #F (ascii currently active indicator) since we are highlighting
# the currently active window using colors
setw -g window-status-format "#I:#W"
setw -g window-status-current-format "#I:#W"

# highlight windows with activity
setw -g monitor-activity on
# setw -g window-status-activity-bg '#CAD5E1'
# display a status line message when activity occurs in a window for
# which the monitor-activity window option is enabled.
set -g visual-activity on

set -g history-limit 1000000

# Enable mouse control
set -g mouse on
